version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

parameters:
  build-image:
    type: string
    default: "circleci/node:13.8.0"

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...

jobs:

#  build-frontend:

  build-frontend:
    docker:
      - image: << pipeline.parameters.build-image >>
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd frontend
            npm install
      - run:
          name: Build
          command: |
            cd frontend
            npm run build

#  build-backend:

  build-backend:
    docker:
      - image: << pipeline.parameters.build-image >>
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd backend
            npm install
      - run:
          name: Build
          command: |
            cd backend
            npm run build

#  test-frontend:

#  test-backend:

#  scan-frontend:

#  scan-backend:

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:  

#  smoke-test:

#  cloudfront-update:

workflows:
  backend:
    jobs:
      - build-backend
      - test-backend:
          requires:
            - build-backend
      - analyze-backend:
          requires:
            - test-backend
      - create_backend_infrastructure:
          requires:
            - analyze-backend

  frontend:
    jobs:
      - build-frontend
      - test-frontend:
          requires:
            - build-frontend
      - analyze-frontend:
          requires:
            - test-frontend
      - create_frontend_infrastructure:
          requires:
            - analyze-frontend
