---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: "install dependencies for server."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install python."
  become: true
  apt:
    name: ["python3"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Insert/Update ENVIRONMENT variables surrounded by custom markers after <body> line
  blockinfile:
    path: ~/.profile
    block: |
      export ENVIRONMENT=production
      export TYPEORM_CONNECTION=postgres
      export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
      export TYPEORM_HOST=localhost
      export TYPEORM_PORT=5532
      export TYPEORM_USERNAME=postgres
      export TYPEORM_PASSWORD=password
      export TYPEORM_DATABASE=glee
    marker: "# {mark} ANSIBLE MANAGED BLOCK "

